name: txfb_insurance_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_settings: '5.1.1'
  bloc: '8.1.2'
  cached_network_image: '3.3.0'
  cross_file: '0.3.3+5'
  custom_refresh_indicator: '2.2.1'
  device_preview: '1.1.0'
  dio: '5.3.3'
  disk_space: '0.2.1'
  equatable: '2.0.5'
  file: '6.1.4'
  firebase_analytics: '10.6.1'
  firebase_core: '2.19.0'
  firebase_crashlytics: '3.4.1'
  flutter:
    sdk: flutter
  flutter_bloc: '8.1.3'
  flutter_driver:
    sdk: flutter
  flutter_inappwebview: '5.8.0'
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: '8.1.0'
  go_router: '11.1.2'
  google_fonts: '6.1.0'
  hive: '2.2.3'
  hive_flutter: '1.1.0'
  http: '1.1.0'
  image: '4.1.3'
  image_picker: '1.0.4'
  intl: '0.18.1'
  json_annotation: '4.8.1'
  local_auth: '2.1.7'
  logger: '2.0.2+1'
  mask_text_input_formatter: '2.5.0'
  mixpanel_flutter: '2.1.1'
  package_info_plus: '4.1.0'
  path_provider: '2.1.1'
  pdf_render: '1.4.0'
  permission_handler: '10.4.5'
  # x-haven `develop` branch, commit hash: 01b1edc218bba83a0d4ad9f2077d1ef4be928398
  plugin_haven:
    path: ./plugin_haven
  provider: '6.0.5'
  retrofit: '4.0.3'
  share_plus: '7.2.1'
  shared_preferences: '2.2.1'
  timezone: '0.9.2'
  url_launcher: '6.1.14'
  visibility_detector: '0.4.0+2'
  workmanager: '0.5.2'

dependency_overrides:
  http: '1.1.0' # plugin_haven
  # Working around Xcode15 issue in flutter_inappwebview.
  # https://github.com/pichillilorenzo/flutter_inappwebview/issues/1735
  # Remove Podfile workaround when fixed.
  # Override is not strictly needed beyond highlighting this.
  flutter_inappwebview: '5.8.0'

dev_dependencies:
  bloc_test: '9.1.4'
  build_runner: '2.4.6'
  flutter_lints: '3.0.0'
  flutter_test:
    sdk: flutter
  json_serializable: '6.7.1'
  local_auth_platform_interface: null
  mocktail: '1.0.1'
  retrofit_generator: '8.0.1'
  test: '1.24.3'

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: benton_sans
      fonts:
        - asset: lib/resources/assets/fonts/benton_sans_book.ttf
        - asset: lib/resources/assets/fonts/benton_sans_bold.ttf
        - asset: lib/resources/assets/fonts/benton_sans_light.ttf
        - asset: lib/resources/assets/fonts/benton_sans_book_italic.ttf
          style: italic
    - family: libre_franklin
      fonts:
        - asset: lib/resources/assets/fonts/LibreFranklin-Black.ttf
        - asset: lib/resources/assets/fonts/LibreFranklin-Bold.ttf
        - asset: lib/resources/assets/fonts/LibreFranklin-ExtraBold.ttf
        - asset: lib/resources/assets/fonts/LibreFranklin-ExtraLight.ttf
        - asset: lib/resources/assets/fonts/LibreFranklin-Light.ttf
        - asset: lib/resources/assets/fonts/LibreFranklin-Medium.ttf
        - asset: lib/resources/assets/fonts/LibreFranklin-Regular.ttf
        - asset: lib/resources/assets/fonts/LibreFranklin-SemiBold.ttf

  assets:
    - lib/resources/assets/fake_data/fake_agents.json
    - lib/resources/assets/images/
    - lib/resources/assets/wallet/txfb.pass/
    - lib/resources/assets/wallet/txfb.gpass.json
